# -*- coding: utf-8 -*-
"""Le bout-en-bout de la reprise, sur deux vraies bases PostgreSQL.

CE QUE CETTE RECETTE PROUVE, ET QUE LES RÈGLES NE PEUVENT PAS PROUVER. Les
règles de `tests/test_reprise_registre.py` tiennent des propriétés du code.
Elles ne peuvent pas dire si la reprise perd des lignes : cela demande deux
bases, des données, et une comparaison après coup. C'est ici.

ELLE A TROUVÉ QUATRE DÉFAUTS, tous invisibles à la lecture du code :

  1. 112 lignes restées au sol — six tables absentes de la destination, deux
     refusées faute de clé, soixante fragments orphelins — et l'outil rendait
     0 en annonçant « transaction validée ».
  2. Le constat annonçait 0 fragment ; l'exécution en copiait 1 410.
  3. Les 1 410 fragments repris n'avaient aucun `search_vector` : la recherche
     plein texte y trouvait ZÉRO résultat sur 1 410.
  4. Trois documents homonymes entraient ensemble, deux repartaient sans un
     seul fragment.

SUBSTITUTION DÉCLARÉE. `pgvector` n'étant pas toujours installé, `vector(1024)`
devient `real[]`. Cette recette éprouve la LOGIQUE DE COPIE, pas pgvector : le
type est traversé à l'identique par psycopg dans les deux cas. Si vous voulez
couvrir pgvector, installez l'extension et retirez la substitution.

    python3 outils/recette_reprise_registre.py            # monte, joue, vérifie
    python3 outils/recette_reprise_registre.py --garder   # ne démonte pas

Elle a besoin d'un PostgreSQL joignable. Par défaut elle en démarre un, à un
chemin court : la socket Unix de PostgreSQL est bornée à 107 octets.
"""
import io
import os
import re
import subprocess
import sys
import time

RACINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOCLE = os.environ.get("RECETTE_PG_BASE", "/tmp/reprise_pg")
DSN = "host=%s/run port=5433 user=postgres dbname=%%s" % SOCLE
URL = "postgresql://postgres@/%s?host=" + SOCLE + "/run&port=5433"

# Les dix tables que la base VIVANTE n'a pas : app.py ne les crée qu'au
# premier usage de leur propre fonctionnalité, jamais au démarrage.
ABSENTES = ["form_inscriptions", "form_sessions", "ia50_usages", "rgpd_aipd",
            "rgpd_audits", "rgpd_demandes", "rgpd_purge_log",
            "rgpd_registre_site", "rgpd_retention", "stripe_events"]

# Ce que la vivante porte EN PLUS (colonnes ajoutées depuis la bascule).
EN_PLUS = (["ALTER TABLE clients ADD COLUMN IF NOT EXISTS generation_session integer"]
           + ["ALTER TABLE systemes_ia ADD COLUMN IF NOT EXISTS %s text" % c for c in
              ("famille", "modele", "unite_facturation", "volume_entree_mois",
               "volume_sortie_mois", "volume_source", "centre_cout", "classe_tache",
               "leviers")])

# Les comptes RELEVÉS le 5 septembre 2026 sur les deux vraies bases.
ATTENDU_SRC = 1696
ATTENDU_DST = 21


# ── Le schéma : celui de la vraie source, reconstruit ────────────────────
SCHEMA = """
CREATE TABLE clients (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom_entreprise text NOT NULL, email text NOT NULL UNIQUE, mot_de_passe_hash text,
  actif boolean DEFAULT false, date_creation text NOT NULL, derniere_connexion text,
  invitation_token text, invitation_expire text, rgpd_consenti boolean DEFAULT false,
  rgpd_consenti_date text, plan text DEFAULT 'pro', reset_token text, reset_expire text,
  verify_email_token text, verify_email_expire text, stripe_customer_id text,
  stripe_subscription_id text, essai_fin text, essai_relance text);
CREATE TABLE consent_records (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  horodatage text, sujet text, email text, email_hash text, methode text, finalites text,
  politique_version text, ip_hash text, user_agent text, retrait integer DEFAULT 0,
  efface integer DEFAULT 0);
CREATE TABLE email_log (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destinataire text NOT NULL, sujet text, methode text, succes boolean NOT NULL,
  raison_echec text, date_envoi text NOT NULL);
CREATE TABLE empreinte_llm (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  horodatage text, jour text, client_id integer, interne integer DEFAULT 0, module text,
  fournisseur text, modele text, tokens_in integer, tokens_out integer, latence_ms integer,
  wh_a real, g_a real, wh_b real, g_b real, g_b_min real, g_b_max real, wh_c real,
  g_c real, g_c_min real, g_c_max real, intensite real, source_intensite text, methodo text);
CREATE TABLE empreinte_web (jour text PRIMARY KEY, pages integer DEFAULT 0,
  octets bigint DEFAULT 0, duree_ms bigint DEFAULT 0);
CREATE TABLE form_sessions (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formation_id integer, date_session text, lieu text, prix_cents integer,
  places integer DEFAULT 12, actif integer DEFAULT 1, date_fin text);
CREATE TABLE form_inscriptions (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id integer, client_id integer, nom text, prenom text, email text, entreprise text,
  fonction text, telephone text, participants integer, message text, montant_cents integer,
  statut text, stripe_session_id text, created_at text);
CREATE TABLE ia50_usages (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  systeme text, role text, contenu text, marquage text, etiquetage text, exception text,
  responsable text, conforme integer DEFAULT 0, date_maj text);
CREATE TABLE client_notes (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL, note text NOT NULL, author text, created_at text NOT NULL);
CREATE TABLE raas_contracts (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL, reference text NOT NULL UNIQUE, envelope_total integer,
  milestones_count integer, status text NOT NULL DEFAULT 'brouillon', content_json text,
  created_at text NOT NULL, signed_at text);
CREATE TABLE raas_milestones (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL, milestone_id text NOT NULL, label text NOT NULL, art text,
  weight real NOT NULL, threshold integer NOT NULL, amount_eur integer NOT NULL,
  status text NOT NULL DEFAULT 'pending', score_at_verification real, evidence text,
  verified_at text, invoiced_at text, created_at text NOT NULL,
  UNIQUE (client_id, milestone_id));
CREATE TABLE rgpd_registre_site (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom text, finalite text, base text, donnees text, duree text, destinataires text,
  date_maj text);
CREATE TABLE rgpd_retention (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cible text, libelle text, duree_mois integer, base text, action text,
  actif integer DEFAULT 1, date_maj text);
CREATE TABLE rgpd_traitements (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer, nom text NOT NULL, finalites text, base_legale text, responsable text,
  sous_traitants text, categories_personnes text, categories_donnees text,
  donnees_sensibles text, destinataires text, transferts_hors_ue text,
  duree_conservation text, mesures_securite text, service text,
  statut text DEFAULT 'actif', date_creation text, date_maj text);
CREATE TABLE rgpd_aipd (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, titre text);
CREATE TABLE rgpd_audits (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, hash text);
CREATE TABLE rgpd_demandes (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type text);
CREATE TABLE rgpd_purge_log (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cible text);
CREATE TABLE stripe_events (event_id text PRIMARY KEY, processed_at text);
CREATE TABLE systemes_ia (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom text NOT NULL, finalite text, secteur text, type_systeme text, donnees_utilisees text,
  classification text, justification text, statut_conformite text DEFAULT 'a_evaluer',
  score_risque integer DEFAULT 0, responsable text, fournisseur text, date_creation text,
  date_maj text, client_id integer, cycle_vie text DEFAULT 'production', product_owner text,
  derniere_revue text, service text, roles text, personnes_concernees text,
  transparence_art50 text DEFAULT 'a_evaluer', preuves_conformite text);
CREATE TABLE rag_documents (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom_fichier text NOT NULL, type_mime text NOT NULL, extension text NOT NULL,
  pages_liees text NOT NULL, taille_octets integer NOT NULL, contenu_fichier bytea NOT NULL,
  nb_chunks integer DEFAULT 0, date_upload text NOT NULL, chunks_indexes integer DEFAULT 0,
  statut_indexation text DEFAULT 'termine', theme text DEFAULT '', famille text DEFAULT '',
  entreprise text DEFAULT '', origine text DEFAULT '');
CREATE TABLE rag_chunks (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id integer NOT NULL REFERENCES rag_documents(id) ON DELETE CASCADE,
  chunk_text text NOT NULL, chunk_index integer NOT NULL, embedding real[],
  search_vector tsvector);
"""


def _pg_bin(nom):
    for base in sorted(os.listdir("/usr/lib/postgresql"), reverse=True):
        p = "/usr/lib/postgresql/%s/bin/%s" % (base, nom)
        if os.path.exists(p):
            return p
    raise SystemExit("PostgreSQL introuvable sous /usr/lib/postgresql.")


def _su(commande):
    """PostgreSQL refuse de tourner sous root : on emprunte un compte."""
    if os.geteuid() != 0:
        return subprocess.run(commande, shell=True, capture_output=True, text=True)
    return subprocess.run(["su", os.environ.get("RECETTE_PG_USER", "pgtest"),
                           "-c", commande], capture_output=True, text=True)


def demarrer():
    d, r = SOCLE + "/data", SOCLE + "/run"
    subprocess.run(["rm", "-rf", SOCLE], check=False)
    os.makedirs(d); os.makedirs(r)
    if os.geteuid() == 0:
        u = os.environ.get("RECETTE_PG_USER", "pgtest")
        subprocess.run(["chown", "-R", "%s:%s" % (u, u), SOCLE], check=False)
    os.chmod(d, 0o700)
    _su("%s -D %s -U postgres --auth=trust -E UTF8" % (_pg_bin("initdb"), d))
    _su('%s -D %s -o "-p 5433 -k %s -c listen_addresses=\'\'" -l %s/pg.log start'
        % (_pg_bin("pg_ctl"), d, r, SOCLE))
    for _ in range(40):
        if _su("%s -h %s -p 5433" % (_pg_bin("pg_isready"), r)).returncode == 0:
            break
        time.sleep(0.5)
    else:
        raise SystemExit("PostgreSQL n'a pas démarré. Voir %s/pg.log" % SOCLE)
    for base in ("src", "dst"):
        _su("psql -h %s -p 5433 -U postgres -c 'CREATE DATABASE %s'" % (r, base))


def arreter():
    _su("%s -D %s/data -m immediate stop" % (_pg_bin("pg_ctl"), SOCLE))
    subprocess.run(["rm", "-rf", SOCLE], check=False)


def monter():
    import psycopg
    for base, sans in (("src", ()), ("dst", ABSENTES)):
        ddl = SCHEMA
        for t in sans:
            ddl = re.sub(r"CREATE TABLE %s \(.*?\);\n" % t, "", ddl, flags=re.S)
        with psycopg.connect(DSN % base, autocommit=True) as c:
            c.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
            c.execute(ddl)
            if base == "dst":
                for a in EN_PLUS:
                    c.execute(a)


def peupler():
    import psycopg
    clients = [("c79942474@gmail.com", "Cerf", "gratuit"),
               ("pouteaucecile@gmail.com", "conseil", "gratuit")] \
        + [("test-%d@example.com" % i, "Test %d" % i, "gratuit") for i in range(4)] \
        + [("pouteau.conseilprev@gmail.com", "conseilprev", "gratuit"),
           ("pouteauconseilprev@gmail.com", "conseilprev", "gratuit"),
           ("christophe.cerf@outlook.com", "Christophe Cerf", "gratuit"),
           ("christophe.cerf@i-aes.com", "Christophe Cerf", "gratuit"),
           ("alaincerf91@gmail.com", "conseilprev", "gratuit"),
           ("conseilprev@internal.system", "CONSEILPREV", "entreprise"),
           ("cpouteauvoila@gmail.com", "cerf", "entreprise")]
    # 49 documents pour 45 CONTENUS distincts : la structure de doublons
    # relevée sur la vraie base (un fichier en 4 exemplaires, un en 2).
    a, b = b"guide IA generative " * 60, b"analyse de risques " * 60
    docs = ([("doc_%02d.pdf" % i, 1000 * i, b"contenu unique %d " % i * 20)
             for i in range(1, 44)]
            + [("Recommandations_securite_systeme_IAGEN.pdf", 2013873, a)]
            + [("Recommandations_de_securite_pour_un_systeme_d_IA_generative.pdf",
                2013873, a)] * 3
            + [("Document_Analyse_de_risques_FR.pdf", 462821, b)]
            + [("Document_Analyse_de_risques_FR_1.pdf", 462821, b)])
    assert len(docs) == 49 and len({d[2] for d in docs}) == 45

    with psycopg.connect(DSN % "src", autocommit=True) as c:
        for e, n, p in clients:
            c.execute("INSERT INTO clients (nom_entreprise,email,plan,date_creation) "
                      "VALUES (%s,%s,%s,'2026-06-24')", (n, e, p))
        for i in range(8):
            c.execute("INSERT INTO consent_records (horodatage,ip_hash,methode,sujet) "
                      "VALUES (%s,%s,'banniere','visiteur')",
                      ("2026-07-%02dT10:00" % (i + 10), "h%02d" % i))
        for i in range(32):
            c.execute("INSERT INTO email_log (destinataire,succes,date_envoi,sujet) "
                      "VALUES (%s,true,'2026-07-01',%s)", ("d%d@x.fr" % i, "s%d" % i))
        for i in range(7):
            c.execute("INSERT INTO empreinte_llm (horodatage,jour,module,modele) "
                      "VALUES (%s,%s,'chat','m')",
                      ("2026-07-%02d" % (i + 1), "2026-07-%02d" % (i + 1)))
        for i in range(45):
            j = ("2026-07-%02d" % (i + 14)) if i < 18 else ("2026-08-%02d" % (i - 17))
            c.execute("INSERT INTO empreinte_web (jour,pages) VALUES (%s,%s)", (j, i))
        c.execute("INSERT INTO form_inscriptions (nom,prenom,email,montant_cents,statut,"
                  "created_at) VALUES ('Cerf','Christophe','christophe.cerf@outlook.com',"
                  "175000,'en_attente_paiement','2026-07-14')")
        for i in range(20):
            c.execute("INSERT INTO form_sessions (formation_id,date_session,prix_cents) "
                      "VALUES (%s,%s,175000)", (i, "2026-09-%02d" % (i + 1)))
        for i in range(5):
            c.execute("INSERT INTO ia50_usages (systeme,role,contenu) VALUES (%s,%s,'t')",
                      ("systeme %d" % i, "deployeur" if i % 2 else "fournisseur"))
        c.execute("INSERT INTO raas_contracts (client_id,reference,status,created_at) "
                  "VALUES (15,'RAAS-15-2026-01','enregistre','2026-07-03')")
        for i in range(21):
            c.execute("INSERT INTO raas_milestones (client_id,milestone_id,label,weight,"
                      "threshold,amount_eur,created_at) VALUES (15,%s,%s,1,50,360,'2026-07-03')",
                      ("j%02d" % i, "jalon %d" % i))
        c.execute("INSERT INTO client_notes (client_id,note,created_at) "
                  "VALUES (15,'Synthese','2026-07-04')")
        for i in range(4):
            c.execute("INSERT INTO stripe_events (event_id,processed_at) "
                      "VALUES (%s,'2026-07-09')", ("evt_%d" % i,))
        for n in ("Chatbot service client", "Scoring credit automatise",
                  "Maintenance predictive reseau", "Assistant vocal IA",
                  "pouteau", "Christophe Cerf"):
            c.execute("INSERT INTO systemes_ia (nom,classification) VALUES (%s,'limite')", (n,))
        for i in range(8):
            c.execute("INSERT INTO rgpd_registre_site (nom,finalite) VALUES (%s,'f')",
                      ("traitement %d" % i,))
        for i in range(4):
            c.execute("INSERT INTO rgpd_retention (cible,libelle,duree_mois) "
                      "VALUES (%s,%s,36)", ("cible%d" % i, "libelle %d" % i))
        c.execute("INSERT INTO rgpd_traitements (nom,client_id) "
                  "VALUES ('Gestion des ressources humaines',15)")
        for nom, taille, contenu in docs:
            did = c.execute(
                "INSERT INTO rag_documents (nom_fichier,type_mime,extension,pages_liees,"
                "taille_octets,contenu_fichier,date_upload) VALUES "
                "(%s,'application/pdf','.pdf','audit',%s,%s,'2026-07-31') RETURNING id",
                (nom, taille, contenu)).fetchone()[0]
            for k in range(30):
                c.execute("INSERT INTO rag_chunks (document_id,chunk_text,chunk_index,"
                          "search_vector) VALUES (%s,%s,%s,to_tsvector('french',%s))",
                          (did, "fragment %d de %s" % (k, nom), k, "fragment %d" % k))

    with psycopg.connect(DSN % "dst", autocommit=True) as c:
        c.execute("INSERT INTO clients (nom_entreprise,email,plan,date_creation) VALUES "
                  "('CONSEILPREV','conseilprev@internal.system','entreprise','2026-08-27')")
        for i in range(2):
            c.execute("INSERT INTO consent_records (horodatage,ip_hash,methode,sujet) "
                      "VALUES (%s,%s,'banniere','visiteur')",
                      ("2026-09-0%dT10:00" % (i + 1), "neuf%d" % i))
        for i in range(3):
            c.execute("INSERT INTO empreinte_llm (horodatage,jour,module,modele) "
                      "VALUES (%s,%s,'chat','m')",
                      ("2026-09-0%d" % (i + 1), "2026-09-0%d" % (i + 1)))
        for i in range(10):
            j = ("2026-08-%02d" % (27 + i)) if i < 5 else ("2026-09-%02d" % (i - 4))
            c.execute("INSERT INTO empreinte_web (jour,pages) VALUES (%s,%s)", (j, i))
        c.execute("INSERT INTO rgpd_traitements (nom,client_id) "
                  "VALUES ('Gestion des ressources humaines',15)")
        for n in ("Chatbot service client", "Scoring credit automatise",
                  "Maintenance predictive reseau", "Detection de fraude"):
            c.execute("INSERT INTO systemes_ia (nom,classification) VALUES (%s,'limite')", (n,))


def _total(base):
    import psycopg
    with psycopg.connect(DSN % base) as c:
        return c.execute(
            "SELECT coalesce(sum((xpath('/row/c/text()', query_to_xml("
            "format('SELECT count(*) AS c FROM public.%I', relname), false, true, '')"
            "))[1]::text::bigint),0) FROM pg_class c JOIN pg_namespace n "
            "ON n.oid=c.relnamespace WHERE n.nspname='public' AND relkind='r'").fetchone()[0]


def _jouer(args=()):
    env = dict(os.environ, REGISTRE_ANCIEN_URL=URL % "src", DATABASE_URL=URL % "dst")
    p = subprocess.run([sys.executable, os.path.join(RACINE, "outils",
                                                     "reprise_registre.py")] + list(args),
                       capture_output=True, text=True, env=env, cwd=RACINE)
    return p.returncode, p.stdout


def _nombre(sortie, motif):
    m = re.search(motif, sortie)
    return int(m.group(1)) if m else None


def main():
    import psycopg
    echecs = []

    def verifier(nom, ok, detail=""):
        print("  %-58s %s" % (nom, "ok" if ok else "ECHEC"))
        if not ok:
            echecs.append("%s %s" % (nom, detail))

    print("Montage des deux bases...")
    demarrer()
    try:
        monter(); peupler()
        print("\n1. LE BANC REPRODUIT LA SITUATION RELEVÉE LE 5 SEPTEMBRE")
        verifier("source : %d lignes" % ATTENDU_SRC, _total("src") == ATTENDU_SRC)
        verifier("destination : %d lignes" % ATTENDU_DST, _total("dst") == ATTENDU_DST)

        print("\n2. LE CONSTAT N'ÉCRIT RIEN ET PRÉDIT L'EXÉCUTION")
        code_c, sortie_c = _jouer()
        avant = _total("dst")
        verifier("le constat n'a rien écrit", avant == ATTENDU_DST, str(avant))
        verifier("le constat ne laisse rien au sol", code_c == 0)
        annonce = _nombre(sortie_c, r"(\d+) ligne\(s\) SERAIENT")

        code_e, sortie_e = _jouer(["--reprendre"])
        fait = _nombre(sortie_e, r"(\d+) ligne\(s\) reprise")
        verifier("constat %s = exécution %s" % (annonce, fait), annonce == fait)
        verifier("l'exécution ne laisse rien au sol", code_e == 0)

        print("\n3. AUCUNE LIGNE N'EST RESTÉE AU SOL")
        with psycopg.connect(DSN % "src") as s, psycopg.connect(DSN % "dst") as d:
            q = ("SELECT relname, (xpath('/row/c/text()', query_to_xml("
                 "format('SELECT count(*) AS c FROM public.%I', relname), false, true,''"
                 ")))[1]::text::bigint FROM pg_class c JOIN pg_namespace n "
                 "ON n.oid=c.relnamespace WHERE n.nspname='public' AND relkind='r'")
            S = dict(s.execute(q).fetchall()); T = dict(d.execute(q).fetchall())
        perdues = {t: (n, T.get(t)) for t, n in S.items()
                   if n and t not in ("rag_documents", "rag_chunks")
                   and (T.get(t) is None or T[t] < n)}
        verifier("aucune table en deçà de la source", not perdues, str(perdues))
        verifier("les 6 tables absentes ont été créées et remplies",
                 all(T.get(t) for t in ("stripe_events", "ia50_usages",
                                        "rgpd_registre_site", "rgpd_retention",
                                        "form_sessions", "form_inscriptions")))

        print("\n4. LE CORPUS EST DÉDOUBLONNÉ, COMPLET ET CHERCHABLE")
        with psycopg.connect(DSN % "dst") as d:
            docs = d.execute("SELECT count(*) FROM rag_documents").fetchone()[0]
            dup = d.execute("SELECT count(*) FROM (SELECT md5(contenu_fichier) "
                            "FROM rag_documents GROUP BY 1 HAVING count(*)>1) x"
                            ).fetchone()[0]
            orph = d.execute("SELECT count(*) FROM rag_documents dd WHERE NOT EXISTS "
                             "(SELECT 1 FROM rag_chunks c WHERE c.document_id=dd.id)"
                             ).fetchone()[0]
            frag = d.execute("SELECT count(*) FROM rag_chunks").fetchone()[0]
            nul = d.execute("SELECT count(*) FROM rag_chunks WHERE search_vector IS NULL"
                            ).fetchone()[0]
            trouve = d.execute("SELECT count(*) FROM rag_chunks WHERE search_vector @@ "
                               "plainto_tsquery('french','fragment')").fetchone()[0]
        verifier("45 documents distincts repris (49 - 4 doublons)", docs == 45, str(docs))
        verifier("aucun contenu en double", dup == 0, str(dup))
        verifier("aucun document sans fragment", orph == 0, str(orph))
        verifier("1350 fragments (45 x 30)", frag == 1350, str(frag))
        verifier("tous les fragments portent leur index plein texte", nul == 0, str(nul))
        verifier("la recherche plein texte les trouve tous", trouve == frag,
                 "%d/%d" % (trouve, frag))

        print("\n5. LA REPRISE EST IDEMPOTENTE")
        apres = _total("dst")
        code2, sortie2 = _jouer(["--reprendre"])
        verifier("un second passage ne reprend rien",
                 _nombre(sortie2, r"(\d+) ligne\(s\) reprise") == 0)
        verifier("le total est inchangé", _total("dst") == apres)
        verifier("et il rend toujours 0", code2 == 0)

        print("\n6. LA SOURCE N'A PAS BOUGÉ")
        verifier("source toujours à %d lignes" % ATTENDU_SRC, _total("src") == ATTENDU_SRC)
    finally:
        if "--garder" not in sys.argv:
            arreter()
        else:
            print("\nBases gardées : %s (psql -h %s/run -p 5433 -U postgres)"
                  % (SOCLE, SOCLE))

    print()
    if echecs:
        print("RECETTE EN ÉCHEC — %d point(s) :" % len(echecs))
        for e in echecs:
            print("  · %s" % e)
        return 1
    print("RECETTE VERTE — la reprise ne perd rien, prédit ce qu'elle fera, "
          "dédoublonne, et se relance sans dommage.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
